[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.3.0"
rust-version = "1.87.0" # Keep this in sync with the requirements!
edition = "2021"
repository = "https://github.com/DLR-FT/wasm-interpreter"
license = "MIT OR Apache-2.0"
authors = ["Florian Hartung <florian.hartung@dlr.de>"]
keywords = ["wasm", "interpreter", "no-std", "embedded", "webassembly"]
categories = ["wasm", "virtualization", "no-std", "embedded"]
exclude = [
  # Nix
  "*.nix",
  "flake.*",
  "pkgs/*",
  ".envrc",
  # CI
  ".github/*",
  "ci-tools/*",
  "codecov.yml",
  # Specification testsuite (too large and contains a git submodule that is not owned by us)
  "tests/wasm_spec_testsuite.rs",
  "tests/specification/*",
  ".gitmodules",
  # Nextest config
  ".config/nextest.toml",
  # TODO: Consider excluding "tests/*" entirely. Currently they are ~780KB large and Cargo's limit
  # is 10MB per crate.
]

[workspace.dependencies]
dlr-wasm-interpreter = { version = "0.3", path = "." }
dlr-wasm-interpreter-checked = { version = "0.3", path = "crates/checked" }
dlr-wasm-interpreter-interop = { version = "0.3", path = "crates/interop" }
dlr-wasm-interpreter-linker = { version = "0.3", path = "crates/linker" }
dlr-wasm-interpreter-registry = { version = "0.3", path = "crates/registry" }

log = "0.4.22"
test-log = { version = "0.2.14", features = ["log"] }
wat = "1.0.83"

[package]
name = "dlr-wasm-interpreter"
description = """
An in-place Wasm interpreter tailored for safety use-cases, such as avionics and automotive applications
"""

edition.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
exclude.workspace = true

[dependencies]
libm = "0.2.8"
log = { workspace = true, optional = true }

[dev-dependencies]
# Crates defined in this workspace
#
# We must specify these using a path so that `cargo package` does not fail. Unfortunately, this
# makes it so that the tests fail in the packaged crate. There are a couple solutions (a combination
# of 1 & 2 is likely the best):
# 1. Make our tests independant of utility crates.
# 2. Move tests that need utility crates to their respective crates.
# 3. Move all tests to a separate crate that does not get published.
dlr-wasm-interpreter-checked = { path = "crates/checked", features = [
  "linker",
  "interop",
] }
dlr-wasm-interpreter-interop = { path = "crates/interop" }
dlr-wasm-interpreter-registry = { path = "crates/registry" }
dlr-wasm-interpreter-linker = { path = "crates/linker" }

# Workspace dependencies
log.workspace = true
wat.workspace = true
test-log = { workspace = true, features = ["log"] }

# Other dependencies
bumpalo = "3.17.0"
hexf = "0.2.1"
envconfig = "0.11.0"
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0"
wast = "212.0.0"

[lints.rust]
missing_docs = "allow"          # TODO change this to warn
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
missing_safety_doc = "warn"
undocumented_unsafe_blocks = "warn"

[lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"
missing_crate_level_docs = "deny"
private_doc_tests = "deny"
invalid_codeblock_attributes = "deny"
invalid_html_tags = "deny"
invalid_rust_codeblocks = "deny"
bare_urls = "deny"
unescaped_backticks = "deny"
redundant_explicit_links = "deny"
