[package]
name = "dlr-wasm-interpreter-linker"
description = """
A name-resolution based linker for dlr-wasm-interpreter
"""

edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
dlr-wasm-interpreter.workspace = true
