[package]
name = "dlr-wasm-interpreter-registry"
description = """
A host function management layer for dlr-wasm-interpreter
"""

edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
dlr-wasm-interpreter.workspace = true
dlr-wasm-interpreter-checked = { workspace = true, features = ["interop"] }
