use crate::{
    config::Config,
    execution::interpreter_loop::{
        control, fc_extensions, fd_extensions, memory, numeric, parametric, reference, table,
        unset, variable, vector, InstructionHandlerFn,
    },
};

pub(crate) trait HasBaseDispatchTable {
    const DISPATCH_TABLE: [InstructionHandlerFn; 256];
}

pub(crate) trait HasFcDispatchTable {
    const FC_DISPATCH_TABLE: [InstructionHandlerFn; 18];
}

pub(crate) trait HasFdDispatchTable {
    const FD_DISPATCH_TABLE: [InstructionHandlerFn; 256];
}

impl<T: Config> HasBaseDispatchTable for T {
    const DISPATCH_TABLE: [InstructionHandlerFn; 256] = [
        control::unreachable::<T>,
        control::nop::<T>,
        control::block::<T>,
        control::r#loop::<T>,
        control::r#if::<T>,
        control::r#else::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        control::end::<T>,
        control::br::<T>,
        control::br_if::<T>,
        control::br_table::<T>,
        control::r#return::<T>,
        control::call::<T>,
        control::call_indirect::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        parametric::drop::<T>,
        parametric::select::<T>,
        parametric::select_t::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        variable::local_get::<T>,
        variable::local_set::<T>,
        variable::local_tee::<T>,
        variable::global_get::<T>,
        variable::global_set::<T>,
        table::table_get::<T>,
        table::table_set::<T>,
        unset::<T>,
        memory::i32_load::<T>,
        memory::i64_load::<T>,
        memory::f32_load::<T>,
        memory::f64_load::<T>,
        memory::i32_load8_s::<T>,
        memory::i32_load8_u::<T>,
        memory::i32_load16_s::<T>,
        memory::i32_load16_u::<T>,
        memory::i64_load8_s::<T>,
        memory::i64_load8_u::<T>,
        memory::i64_load16_s::<T>,
        memory::i64_load16_u::<T>,
        memory::i64_load32_s::<T>,
        memory::i64_load32_u::<T>,
        memory::i32_store::<T>,
        memory::i64_store::<T>,
        memory::f32_store::<T>,
        memory::f64_store::<T>,
        memory::i32_store8::<T>,
        memory::i32_store16::<T>,
        memory::i64_store8::<T>,
        memory::i64_store16::<T>,
        memory::i64_store32::<T>,
        memory::memory_size::<T>,
        memory::memory_grow::<T>,
        numeric::i32_const::<T>,
        numeric::i64_const::<T>,
        numeric::f32_const::<T>,
        numeric::f64_const::<T>,
        numeric::i32_eqz::<T>,
        numeric::i32_eq::<T>,
        numeric::i32_ne::<T>,
        numeric::i32_lt_s::<T>,
        numeric::i32_lt_u::<T>,
        numeric::i32_gt_s::<T>,
        numeric::i32_gt_u::<T>,
        numeric::i32_le_s::<T>,
        numeric::i32_le_u::<T>,
        numeric::i32_ge_s::<T>,
        numeric::i32_ge_u::<T>,
        numeric::i64_eqz::<T>,
        numeric::i64_eq::<T>,
        numeric::i64_ne::<T>,
        numeric::i64_lt_s::<T>,
        numeric::i64_lt_u::<T>,
        numeric::i64_gt_s::<T>,
        numeric::i64_gt_u::<T>,
        numeric::i64_le_s::<T>,
        numeric::i64_le_u::<T>,
        numeric::i64_ge_s::<T>,
        numeric::i64_ge_u::<T>,
        numeric::f32_eq::<T>,
        numeric::f32_ne::<T>,
        numeric::f32_lt::<T>,
        numeric::f32_gt::<T>,
        numeric::f32_le::<T>,
        numeric::f32_ge::<T>,
        numeric::f64_eq::<T>,
        numeric::f64_ne::<T>,
        numeric::f64_lt::<T>,
        numeric::f64_gt::<T>,
        numeric::f64_le::<T>,
        numeric::f64_ge::<T>,
        numeric::i32_clz::<T>,
        numeric::i32_ctz::<T>,
        numeric::i32_popcnt::<T>,
        numeric::i32_add::<T>,
        numeric::i32_sub::<T>,
        numeric::i32_mul::<T>,
        numeric::i32_div_s::<T>,
        numeric::i32_div_u::<T>,
        numeric::i32_rem_s::<T>,
        numeric::i32_rem_u::<T>,
        numeric::i32_and::<T>,
        numeric::i32_or::<T>,
        numeric::i32_xor::<T>,
        numeric::i32_shl::<T>,
        numeric::i32_shr_s::<T>,
        numeric::i32_shr_u::<T>,
        numeric::i32_rotl::<T>,
        numeric::i32_rotr::<T>,
        numeric::i64_clz::<T>,
        numeric::i64_ctz::<T>,
        numeric::i64_popcnt::<T>,
        numeric::i64_add::<T>,
        numeric::i64_sub::<T>,
        numeric::i64_mul::<T>,
        numeric::i64_div_s::<T>,
        numeric::i64_div_u::<T>,
        numeric::i64_rem_s::<T>,
        numeric::i64_rem_u::<T>,
        numeric::i64_and::<T>,
        numeric::i64_or::<T>,
        numeric::i64_xor::<T>,
        numeric::i64_shl::<T>,
        numeric::i64_shr_s::<T>,
        numeric::i64_shr_u::<T>,
        numeric::i64_rotl::<T>,
        numeric::i64_rotr::<T>,
        numeric::f32_abs::<T>,
        numeric::f32_neg::<T>,
        numeric::f32_ceil::<T>,
        numeric::f32_floor::<T>,
        numeric::f32_trunc::<T>,
        numeric::f32_nearest::<T>,
        numeric::f32_sqrt::<T>,
        numeric::f32_add::<T>,
        numeric::f32_sub::<T>,
        numeric::f32_mul::<T>,
        numeric::f32_div::<T>,
        numeric::f32_min::<T>,
        numeric::f32_max::<T>,
        numeric::f32_copysign::<T>,
        numeric::f64_abs::<T>,
        numeric::f64_neg::<T>,
        numeric::f64_ceil::<T>,
        numeric::f64_floor::<T>,
        numeric::f64_trunc::<T>,
        numeric::f64_nearest::<T>,
        numeric::f64_sqrt::<T>,
        numeric::f64_add::<T>,
        numeric::f64_sub::<T>,
        numeric::f64_mul::<T>,
        numeric::f64_div::<T>,
        numeric::f64_min::<T>,
        numeric::f64_max::<T>,
        numeric::f64_copysign::<T>,
        numeric::i32_wrap_i64::<T>,
        numeric::i32_trunc_f32_s::<T>,
        numeric::i32_trunc_f32_u::<T>,
        numeric::i32_trunc_f64_s::<T>,
        numeric::i32_trunc_f64_u::<T>,
        numeric::i64_extend_i32_s::<T>,
        numeric::i64_extend_i32_u::<T>,
        numeric::i64_trunc_f32_s::<T>,
        numeric::i64_trunc_f32_u::<T>,
        numeric::i64_trunc_f64_s::<T>,
        numeric::i64_trunc_f64_u::<T>,
        numeric::f32_convert_i32_s::<T>,
        numeric::f32_convert_i32_u::<T>,
        numeric::f32_convert_i64_s::<T>,
        numeric::f32_convert_i64_u::<T>,
        numeric::f32_demote_f64::<T>,
        numeric::f64_convert_i32_s::<T>,
        numeric::f64_convert_i32_u::<T>,
        numeric::f64_convert_i64_s::<T>,
        numeric::f64_convert_i64_u::<T>,
        numeric::f64_promote_f32::<T>,
        numeric::i32_reinterpret_f32::<T>,
        numeric::i64_reinterpret_f64::<T>,
        numeric::f32_reinterpret_i32::<T>,
        numeric::f64_reinterpret_i64::<T>,
        numeric::i32_extend8_s::<T>,
        numeric::i32_extend16_s::<T>,
        numeric::i64_extend8_s::<T>,
        numeric::i64_extend16_s::<T>,
        numeric::i64_extend32_s::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        reference::ref_null::<T>,
        reference::ref_is_null::<T>,
        reference::ref_func::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        fc_extensions::<T>,
        fd_extensions::<T>,
        unset::<T>,
        unset::<T>,
    ];
}

impl<T: Config> HasFcDispatchTable for T {
    const FC_DISPATCH_TABLE: [InstructionHandlerFn; 18] = [
        numeric::i32_trunc_sat_f32_s::<T>,
        numeric::i32_trunc_sat_f32_u::<T>,
        numeric::i32_trunc_sat_f64_s::<T>,
        numeric::i32_trunc_sat_f64_u::<T>,
        numeric::i64_trunc_sat_f32_s::<T>,
        numeric::i64_trunc_sat_f32_u::<T>,
        numeric::i64_trunc_sat_f64_s::<T>,
        numeric::i64_trunc_sat_f64_u::<T>,
        memory::memory_init_fn::<T>,
        memory::data_drop_fn::<T>,
        memory::memory_copy::<T>,
        memory::memory_fill::<T>,
        table::table_init_fn::<T>,
        table::elem_drop_fn::<T>,
        table::table_copy::<T>,
        table::table_grow::<T>,
        table::table_size::<T>,
        table::table_fill::<T>,
    ];
}

impl<T: Config> HasFdDispatchTable for T {
    const FD_DISPATCH_TABLE: [InstructionHandlerFn; 256] = [
        memory::v128_load::<T>,
        memory::v128_load8x8_s::<T>,
        memory::v128_load8x8_u::<T>,
        memory::v128_load16x4_s::<T>,
        memory::v128_load16x4_u::<T>,
        memory::v128_load32x2_s::<T>,
        memory::v128_load32x2_u::<T>,
        memory::v128_load8_splat::<T>,
        memory::v128_load16_splat::<T>,
        memory::v128_load32_splat::<T>,
        memory::v128_load64_splat::<T>,
        memory::v128_store::<T>,
        vector::v128_const::<T>,
        vector::i8x16_shuffle::<T>,
        vector::i8x16_swizzle::<T>,
        vector::i8x16_splat::<T>,
        vector::i16x8_splat::<T>,
        vector::i32x4_splat::<T>,
        vector::i64x2_splat::<T>,
        vector::f32x4_splat::<T>,
        vector::f64x2_splat::<T>,
        vector::i8x16_extract_lane_s::<T>,
        vector::i8x16_extract_lane_u::<T>,
        vector::i8x16_replace_lane::<T>,
        vector::i16x8_extract_lane_s::<T>,
        vector::i16x8_extract_lane_u::<T>,
        vector::i16x8_replace_lane::<T>,
        vector::i32x4_extract_lane::<T>,
        vector::i32x4_replace_lane::<T>,
        vector::i64x2_extract_lane::<T>,
        vector::i64x2_replace_lane::<T>,
        vector::f32x4_extract_lane::<T>,
        vector::f32x4_replace_lane::<T>,
        vector::f64x2_extract_lane::<T>,
        vector::f64x2_replace_lane::<T>,
        // 35
        vector::i8x16_eq::<T>,
        vector::i8x16_ne::<T>,
        vector::i8x16_lt_s::<T>,
        vector::i8x16_lt_u::<T>,
        vector::i8x16_gt_s::<T>,
        vector::i8x16_gt_u::<T>,
        vector::i8x16_le_s::<T>,
        vector::i8x16_le_u::<T>,
        vector::i8x16_ge_s::<T>,
        vector::i8x16_ge_u::<T>,
        // 45
        vector::i16x8_eq::<T>,
        vector::i16x8_ne::<T>,
        vector::i16x8_lt_s::<T>,
        vector::i16x8_lt_u::<T>,
        vector::i16x8_gt_s::<T>,
        vector::i16x8_gt_u::<T>,
        vector::i16x8_le_s::<T>,
        vector::i16x8_le_u::<T>,
        vector::i16x8_ge_s::<T>,
        vector::i16x8_ge_u::<T>,
        // 55
        vector::i32x4_eq::<T>,
        vector::i32x4_ne::<T>,
        vector::i32x4_lt_s::<T>,
        vector::i32x4_lt_u::<T>,
        vector::i32x4_gt_s::<T>,
        vector::i32x4_gt_u::<T>,
        vector::i32x4_le_s::<T>,
        vector::i32x4_le_u::<T>,
        vector::i32x4_ge_s::<T>,
        vector::i32x4_ge_u::<T>,
        // 65
        vector::f32x4_eq::<T>,
        vector::f32x4_ne::<T>,
        vector::f32x4_lt::<T>,
        vector::f32x4_gt::<T>,
        vector::f32x4_le::<T>,
        vector::f32x4_ge::<T>,
        // 71
        vector::f64x2_eq::<T>,
        vector::f64x2_ne::<T>,
        vector::f64x2_lt::<T>,
        vector::f64x2_gt::<T>,
        vector::f64x2_le::<T>,
        vector::f64x2_ge::<T>,
        // 77
        vector::v128_not::<T>,
        vector::v128_and::<T>,
        vector::v128_andnot::<T>,
        vector::v128_or::<T>,
        vector::v128_xor::<T>,
        vector::v128_bitselect::<T>,
        vector::v128_any_true::<T>,
        // 84
        memory::v128_load8_lane::<T>,
        memory::v128_load16_lane::<T>,
        memory::v128_load32_lane::<T>,
        memory::v128_load64_lane::<T>,
        memory::v128_store8_lane::<T>,
        memory::v128_store16_lane::<T>,
        memory::v128_store32_lane::<T>,
        memory::v128_store64_lane::<T>,
        memory::v128_load32_zero::<T>,
        memory::v128_load64_zero::<T>,
        // 94
        vector::f32x4_demote_f64x2_zero::<T>,
        vector::f64x2_promote_low_f32x4::<T>,
        // 96
        vector::i8x16_abs::<T>,
        vector::i8x16_neg::<T>,
        vector::i8x16_popcnt::<T>,
        vector::i8x16_all_true::<T>,
        vector::i8x16_bitmask::<T>,
        vector::i8x16_narrow_i16x8_s::<T>,
        vector::i8x16_narrow_i16x8_u::<T>,
        // 103
        vector::f32x4_ceil::<T>,
        vector::f32x4_floor::<T>,
        vector::f32x4_trunc::<T>,
        vector::f32x4_nearest::<T>,
        // 107
        vector::i8x16_shl::<T>,
        vector::i8x16_shr_s::<T>,
        vector::i8x16_shr_u::<T>,
        vector::i8x16_add::<T>,
        vector::i8x16_add_sat_s::<T>,
        vector::i8x16_add_sat_u::<T>,
        vector::i8x16_sub::<T>,
        vector::i8x16_sub_sat_s::<T>,
        vector::i8x16_sub_sat_u::<T>,
        // 116
        vector::f64x2_ceil::<T>,
        vector::f64x2_floor::<T>,
        // 118
        vector::i8x16_min_s::<T>,
        vector::i8x16_min_u::<T>,
        vector::i8x16_max_s::<T>,
        vector::i8x16_max_u::<T>,
        // 122
        vector::f64x2_trunc::<T>,
        // 123
        vector::i8x16_avgr_u::<T>,
        // 124
        vector::i16x8_extadd_pairwise_i8x16_s::<T>,
        vector::i16x8_extadd_pairwise_i8x16_u::<T>,
        // 126
        vector::i32x4_extadd_pairwise_i16x8_s::<T>,
        vector::i32x4_extadd_pairwise_i16x8_u::<T>,
        // 128
        vector::i16x8_abs::<T>,
        vector::i16x8_neg::<T>,
        vector::i16x8_q15mulrsat_s::<T>,
        vector::i16x8_all_true::<T>,
        vector::i16x8_bitmask::<T>,
        vector::i16x8_narrow_i32x4_s::<T>,
        vector::i16x8_narrow_i32x4_u::<T>,
        vector::i16x8_extend_low_i8x16_s::<T>,
        vector::i16x8_extend_high_i8x16_s::<T>,
        vector::i16x8_extend_low_i8x16_u::<T>,
        vector::i16x8_extend_high_i8x16_u::<T>,
        vector::i16x8_shl::<T>,
        vector::i16x8_shr_s::<T>,
        vector::i16x8_shr_u::<T>,
        vector::i16x8_add::<T>,
        vector::i16x8_add_sat_s::<T>,
        vector::i16x8_add_sat_u::<T>,
        vector::i16x8_sub::<T>,
        vector::i16x8_sub_sat_s::<T>,
        vector::i16x8_sub_sat_u::<T>,
        // 148
        vector::f64x2_nearest::<T>,
        // 149
        vector::i16x8_mul::<T>,
        vector::i16x8_min_s::<T>,
        vector::i16x8_min_u::<T>,
        vector::i16x8_max_s::<T>,
        vector::i16x8_max_u::<T>,
        // 154
        unset::<T>,
        // 155
        vector::i16x8_avgr_u::<T>,
        vector::i16x8_extmul_low_i8x16_s::<T>,
        vector::i16x8_extmul_high_i8x16_s::<T>,
        vector::i16x8_extmul_low_i8x16_u::<T>,
        vector::i16x8_extmul_high_i8x16_u::<T>,
        // 160
        vector::i32x4_abs::<T>,
        vector::i32x4_neg::<T>,
        // 162
        unset::<T>,
        // 163
        vector::i32x4_all_true::<T>,
        vector::i32x4_bitmask::<T>,
        // 165,
        unset::<T>,
        unset::<T>,
        // 167
        vector::i32x4_extend_low_i16x8_s::<T>,
        vector::i32x4_extend_high_i16x8_s::<T>,
        vector::i32x4_extend_low_i16x8_u::<T>,
        vector::i32x4_extend_high_i16x8_u::<T>,
        vector::i32x4_shl::<T>,
        vector::i32x4_shr_s::<T>,
        vector::i32x4_shr_u::<T>,
        vector::i32x4_add::<T>,
        // 175
        unset::<T>,
        unset::<T>,
        // 177
        vector::i32x4_sub::<T>,
        // 178
        unset::<T>,
        unset::<T>,
        unset::<T>,
        // 181
        vector::i32x4_mul::<T>,
        vector::i32x4_min_s::<T>,
        vector::i32x4_min_u::<T>,
        vector::i32x4_max_s::<T>,
        vector::i32x4_max_u::<T>,
        vector::i32x4_dot_i16x8_s::<T>,
        // 187
        unset::<T>,
        // 188
        vector::i32x4_extmul_low_i16x8_s::<T>,
        vector::i32x4_extmul_high_i16x8_s::<T>,
        vector::i32x4_extmul_low_i16x8_u::<T>,
        vector::i32x4_extmul_high_i16x8_u::<T>,
        // 192
        vector::i64x2_abs::<T>,
        vector::i64x2_neg::<T>,
        // 194
        unset::<T>,
        // 195
        vector::i64x2_all_true::<T>,
        vector::i64x2_bitmask::<T>,
        // 197
        unset::<T>,
        unset::<T>,
        // 199
        vector::i64x2_extend_low_i32x4_s::<T>,
        vector::i64x2_extend_high_i32x4_s::<T>,
        vector::i64x2_extend_low_i32x4_u::<T>,
        vector::i64x2_extend_high_i32x4_u::<T>,
        vector::i64x2_shl::<T>,
        vector::i64x2_shr_s::<T>,
        vector::i64x2_shr_u::<T>,
        vector::i64x2_add::<T>,
        // 207
        unset::<T>,
        unset::<T>,
        // 209
        vector::i64x2_sub::<T>,
        // 210
        unset::<T>,
        unset::<T>,
        unset::<T>,
        // 213
        vector::i64x2_mul::<T>,
        // 214
        vector::i64x2_eq::<T>,
        vector::i64x2_ne::<T>,
        vector::i64x2_lt_s::<T>,
        vector::i64x2_gt_s::<T>,
        vector::i64x2_le_s::<T>,
        vector::i64x2_ge_s::<T>,
        // 220
        vector::i64x2_extmul_low_i32x4_s::<T>,
        vector::i64x2_extmul_high_i32x4_s::<T>,
        vector::i64x2_extmul_low_i32x4_u::<T>,
        vector::i64x2_extmul_high_i32x4_u::<T>,
        // 224
        vector::f32x4_abs::<T>,
        vector::f32x4_neg::<T>,
        // 226
        unset::<T>,
        // 227
        vector::f32x4_sqrt::<T>,
        vector::f32x4_add::<T>,
        vector::f32x4_sub::<T>,
        vector::f32x4_mul::<T>,
        vector::f32x4_div::<T>,
        vector::f32x4_min::<T>,
        vector::f32x4_max::<T>,
        vector::f32x4_pmin::<T>,
        vector::f32x4_pmax::<T>,
        // 236
        vector::f64x2_abs::<T>,
        vector::f64x2_neg::<T>,
        // 238
        unset::<T>,
        // 239
        vector::f64x2_sqrt::<T>,
        vector::f64x2_add::<T>,
        vector::f64x2_sub::<T>,
        vector::f64x2_mul::<T>,
        vector::f64x2_div::<T>,
        vector::f64x2_min::<T>,
        vector::f64x2_max::<T>,
        vector::f64x2_pmin::<T>,
        vector::f64x2_pmax::<T>,
        // 248
        vector::i32x4_trunc_sat_f32x4_s::<T>,
        vector::i32x4_trunc_sat_f32x4_u::<T>,
        // 250
        vector::f32x4_convert_i32x4_s::<T>,
        vector::f32x4_convert_i32x4_u::<T>,
        // 252
        vector::i32x4_trunc_sat_f64x2_s_zero::<T>,
        vector::i32x4_trunc_sat_f64x2_u_zero::<T>,
        // 254
        vector::f64x2_convert_low_i32x4_s::<T>,
        vector::f64x2_convert_low_i32x4_u::<T>,
        // todo
    ];
}
