use crate::{
    config::Config,
    execution::interpreter_loop::{
        control_instructions, fc_extensions, fd_extensions, memory_instructions,
        numeric_instructions, parametric_instructions, reference_instructions, table_instructions,
        unset, variable_instructions, vector_instructions, InstructionHandlerFn,
    },
};

pub(crate) trait HasBaseDispatchTable<T> {
    const DISPATCH_TABLE: [InstructionHandlerFn<T>; 256];
}

pub(crate) trait HasFcDispatchTable<T> {
    const FC_DISPATCH_TABLE: [InstructionHandlerFn<T>; 18];
}

pub(crate) trait HasFdDispatchTable<T> {
    const FD_DISPATCH_TABLE: [InstructionHandlerFn<T>; 256];
}

impl<T: Config> HasBaseDispatchTable<T> for T {
    const DISPATCH_TABLE: [InstructionHandlerFn<T>; 256] = [
        control_instructions::unreachable::<T>,
        control_instructions::nop::<T>,
        control_instructions::block::<T>,
        control_instructions::r#loop::<T>,
        control_instructions::r#if::<T>,
        control_instructions::r#else::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        control_instructions::end::<T>,
        control_instructions::br::<T>,
        control_instructions::br_if::<T>,
        control_instructions::br_table::<T>,
        control_instructions::r#return::<T>,
        control_instructions::call::<T>,
        control_instructions::call_indirect::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        parametric_instructions::drop::<T>,
        parametric_instructions::select::<T>,
        parametric_instructions::select_t::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        variable_instructions::local_get::<T>,
        variable_instructions::local_set::<T>,
        variable_instructions::local_tee::<T>,
        variable_instructions::global_get::<T>,
        variable_instructions::global_set::<T>,
        table_instructions::table_get::<T>,
        table_instructions::table_set::<T>,
        unset::<T>,
        memory_instructions::i32_load::<T>,
        memory_instructions::i64_load::<T>,
        memory_instructions::f32_load::<T>,
        memory_instructions::f64_load::<T>,
        memory_instructions::i32_load8_s::<T>,
        memory_instructions::i32_load8_u::<T>,
        memory_instructions::i32_load16_s::<T>,
        memory_instructions::i32_load16_u::<T>,
        memory_instructions::i64_load8_s::<T>,
        memory_instructions::i64_load8_u::<T>,
        memory_instructions::i64_load16_s::<T>,
        memory_instructions::i64_load16_u::<T>,
        memory_instructions::i64_load32_s::<T>,
        memory_instructions::i64_load32_u::<T>,
        memory_instructions::i32_store::<T>,
        memory_instructions::i64_store::<T>,
        memory_instructions::f32_store::<T>,
        memory_instructions::f64_store::<T>,
        memory_instructions::i32_store8::<T>,
        memory_instructions::i32_store16::<T>,
        memory_instructions::i64_store8::<T>,
        memory_instructions::i64_store16::<T>,
        memory_instructions::i64_store32::<T>,
        memory_instructions::memory_size::<T>,
        memory_instructions::memory_grow::<T>,
        numeric_instructions::i32_const::<T>,
        numeric_instructions::i64_const::<T>,
        numeric_instructions::f32_const::<T>,
        numeric_instructions::f64_const::<T>,
        numeric_instructions::i32_eqz::<T>,
        numeric_instructions::i32_eq::<T>,
        numeric_instructions::i32_ne::<T>,
        numeric_instructions::i32_lt_s::<T>,
        numeric_instructions::i32_lt_u::<T>,
        numeric_instructions::i32_gt_s::<T>,
        numeric_instructions::i32_gt_u::<T>,
        numeric_instructions::i32_le_s::<T>,
        numeric_instructions::i32_le_u::<T>,
        numeric_instructions::i32_ge_s::<T>,
        numeric_instructions::i32_ge_u::<T>,
        numeric_instructions::i64_eqz::<T>,
        numeric_instructions::i64_eq::<T>,
        numeric_instructions::i64_ne::<T>,
        numeric_instructions::i64_lt_s::<T>,
        numeric_instructions::i64_lt_u::<T>,
        numeric_instructions::i64_gt_s::<T>,
        numeric_instructions::i64_gt_u::<T>,
        numeric_instructions::i64_le_s::<T>,
        numeric_instructions::i64_le_u::<T>,
        numeric_instructions::i64_ge_s::<T>,
        numeric_instructions::i64_ge_u::<T>,
        numeric_instructions::f32_eq::<T>,
        numeric_instructions::f32_ne::<T>,
        numeric_instructions::f32_lt::<T>,
        numeric_instructions::f32_gt::<T>,
        numeric_instructions::f32_le::<T>,
        numeric_instructions::f32_ge::<T>,
        numeric_instructions::f64_eq::<T>,
        numeric_instructions::f64_ne::<T>,
        numeric_instructions::f64_lt::<T>,
        numeric_instructions::f64_gt::<T>,
        numeric_instructions::f64_le::<T>,
        numeric_instructions::f64_ge::<T>,
        numeric_instructions::i32_clz::<T>,
        numeric_instructions::i32_ctz::<T>,
        numeric_instructions::i32_popcnt::<T>,
        numeric_instructions::i32_add::<T>,
        numeric_instructions::i32_sub::<T>,
        numeric_instructions::i32_mul::<T>,
        numeric_instructions::i32_div_s::<T>,
        numeric_instructions::i32_div_u::<T>,
        numeric_instructions::i32_rem_s::<T>,
        numeric_instructions::i32_rem_u::<T>,
        numeric_instructions::i32_and::<T>,
        numeric_instructions::i32_or::<T>,
        numeric_instructions::i32_xor::<T>,
        numeric_instructions::i32_shl::<T>,
        numeric_instructions::i32_shr_s::<T>,
        numeric_instructions::i32_shr_u::<T>,
        numeric_instructions::i32_rotl::<T>,
        numeric_instructions::i32_rotr::<T>,
        numeric_instructions::i64_clz::<T>,
        numeric_instructions::i64_ctz::<T>,
        numeric_instructions::i64_popcnt::<T>,
        numeric_instructions::i64_add::<T>,
        numeric_instructions::i64_sub::<T>,
        numeric_instructions::i64_mul::<T>,
        numeric_instructions::i64_div_s::<T>,
        numeric_instructions::i64_div_u::<T>,
        numeric_instructions::i64_rem_s::<T>,
        numeric_instructions::i64_rem_u::<T>,
        numeric_instructions::i64_and::<T>,
        numeric_instructions::i64_or::<T>,
        numeric_instructions::i64_xor::<T>,
        numeric_instructions::i64_shl::<T>,
        numeric_instructions::i64_shr_s::<T>,
        numeric_instructions::i64_shr_u::<T>,
        numeric_instructions::i64_rotl::<T>,
        numeric_instructions::i64_rotr::<T>,
        numeric_instructions::f32_abs::<T>,
        numeric_instructions::f32_neg::<T>,
        numeric_instructions::f32_ceil::<T>,
        numeric_instructions::f32_floor::<T>,
        numeric_instructions::f32_trunc::<T>,
        numeric_instructions::f32_nearest::<T>,
        numeric_instructions::f32_sqrt::<T>,
        numeric_instructions::f32_add::<T>,
        numeric_instructions::f32_sub::<T>,
        numeric_instructions::f32_mul::<T>,
        numeric_instructions::f32_div::<T>,
        numeric_instructions::f32_min::<T>,
        numeric_instructions::f32_max::<T>,
        numeric_instructions::f32_copysign::<T>,
        numeric_instructions::f64_abs::<T>,
        numeric_instructions::f64_neg::<T>,
        numeric_instructions::f64_ceil::<T>,
        numeric_instructions::f64_floor::<T>,
        numeric_instructions::f64_trunc::<T>,
        numeric_instructions::f64_nearest::<T>,
        numeric_instructions::f64_sqrt::<T>,
        numeric_instructions::f64_add::<T>,
        numeric_instructions::f64_sub::<T>,
        numeric_instructions::f64_mul::<T>,
        numeric_instructions::f64_div::<T>,
        numeric_instructions::f64_min::<T>,
        numeric_instructions::f64_max::<T>,
        numeric_instructions::f64_copysign::<T>,
        numeric_instructions::i32_wrap_i64::<T>,
        numeric_instructions::i32_trunc_f32_s::<T>,
        numeric_instructions::i32_trunc_f32_u::<T>,
        numeric_instructions::i32_trunc_f64_s::<T>,
        numeric_instructions::i32_trunc_f64_u::<T>,
        numeric_instructions::i64_extend_i32_s::<T>,
        numeric_instructions::i64_extend_i32_u::<T>,
        numeric_instructions::i64_trunc_f32_s::<T>,
        numeric_instructions::i64_trunc_f32_u::<T>,
        numeric_instructions::i64_trunc_f64_s::<T>,
        numeric_instructions::i64_trunc_f64_u::<T>,
        numeric_instructions::f32_convert_i32_s::<T>,
        numeric_instructions::f32_convert_i32_u::<T>,
        numeric_instructions::f32_convert_i64_s::<T>,
        numeric_instructions::f32_convert_i64_u::<T>,
        numeric_instructions::f32_demote_f64::<T>,
        numeric_instructions::f64_convert_i32_s::<T>,
        numeric_instructions::f64_convert_i32_u::<T>,
        numeric_instructions::f64_convert_i64_s::<T>,
        numeric_instructions::f64_convert_i64_u::<T>,
        numeric_instructions::f64_promote_f32::<T>,
        numeric_instructions::i32_reinterpret_f32::<T>,
        numeric_instructions::i64_reinterpret_f64::<T>,
        numeric_instructions::f32_reinterpret_i32::<T>,
        numeric_instructions::f64_reinterpret_i64::<T>,
        numeric_instructions::i32_extend8_s::<T>,
        numeric_instructions::i32_extend16_s::<T>,
        numeric_instructions::i64_extend8_s::<T>,
        numeric_instructions::i64_extend16_s::<T>,
        numeric_instructions::i64_extend32_s::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        reference_instructions::ref_null::<T>,
        reference_instructions::ref_is_null::<T>,
        reference_instructions::ref_func::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        unset::<T>,
        fc_extensions::<T>,
        fd_extensions::<T>,
        unset::<T>,
        unset::<T>,
    ];
}

impl<T: Config> HasFcDispatchTable<T> for T {
    const FC_DISPATCH_TABLE: [InstructionHandlerFn<T>; 18] = [
        numeric_instructions::i32_trunc_sat_f32_s::<T>,
        numeric_instructions::i32_trunc_sat_f32_u::<T>,
        numeric_instructions::i32_trunc_sat_f64_s::<T>,
        numeric_instructions::i32_trunc_sat_f64_u::<T>,
        numeric_instructions::i64_trunc_sat_f32_s::<T>,
        numeric_instructions::i64_trunc_sat_f32_u::<T>,
        numeric_instructions::i64_trunc_sat_f64_s::<T>,
        numeric_instructions::i64_trunc_sat_f64_u::<T>,
        memory_instructions::memory_init_fn::<T>,
        memory_instructions::data_drop_fn::<T>,
        memory_instructions::memory_copy::<T>,
        memory_instructions::memory_fill::<T>,
        table_instructions::table_init_fn::<T>,
        table_instructions::elem_drop_fn::<T>,
        table_instructions::table_copy::<T>,
        table_instructions::table_grow::<T>,
        table_instructions::table_size::<T>,
        table_instructions::table_fill::<T>,
    ];
}

impl<T: Config> HasFdDispatchTable<T> for T {
    const FD_DISPATCH_TABLE: [InstructionHandlerFn<T>; 256] = [
        memory_instructions::v128_load::<T>,
        memory_instructions::v128_load8x8_s::<T>,
        memory_instructions::v128_load8x8_u::<T>,
        memory_instructions::v128_load16x4_s::<T>,
        memory_instructions::v128_load16x4_u::<T>,
        memory_instructions::v128_load32x2_s::<T>,
        memory_instructions::v128_load32x2_u::<T>,
        memory_instructions::v128_load8_splat::<T>,
        memory_instructions::v128_load16_splat::<T>,
        memory_instructions::v128_load32_splat::<T>,
        memory_instructions::v128_load64_splat::<T>,
        memory_instructions::v128_store::<T>,
        vector_instructions::v128_const::<T>,
        vector_instructions::i8x16_shuffle::<T>,
        vector_instructions::i8x16_swizzle::<T>,
        vector_instructions::i8x16_splat::<T>,
        vector_instructions::i16x8_splat::<T>,
        vector_instructions::i32x4_splat::<T>,
        vector_instructions::i64x2_splat::<T>,
        vector_instructions::f32x4_splat::<T>,
        vector_instructions::f64x2_splat::<T>,
        vector_instructions::i8x16_extract_lane_s::<T>,
        vector_instructions::i8x16_extract_lane_u::<T>,
        vector_instructions::i8x16_replace_lane::<T>,
        vector_instructions::i16x8_extract_lane_s::<T>,
        vector_instructions::i16x8_extract_lane_u::<T>,
        vector_instructions::i16x8_replace_lane::<T>,
        vector_instructions::i32x4_extract_lane::<T>,
        vector_instructions::i32x4_replace_lane::<T>,
        vector_instructions::i64x2_extract_lane::<T>,
        vector_instructions::i64x2_replace_lane::<T>,
        vector_instructions::f32x4_extract_lane::<T>,
        vector_instructions::f32x4_replace_lane::<T>,
        vector_instructions::f64x2_extract_lane::<T>,
        vector_instructions::f64x2_replace_lane::<T>,
        // 35
        vector_instructions::i8x16_eq::<T>,
        vector_instructions::i8x16_ne::<T>,
        vector_instructions::i8x16_lt_s::<T>,
        vector_instructions::i8x16_lt_u::<T>,
        vector_instructions::i8x16_gt_s::<T>,
        vector_instructions::i8x16_gt_u::<T>,
        vector_instructions::i8x16_le_s::<T>,
        vector_instructions::i8x16_le_u::<T>,
        vector_instructions::i8x16_ge_s::<T>,
        vector_instructions::i8x16_ge_u::<T>,
        // 45
        vector_instructions::i16x8_eq::<T>,
        vector_instructions::i16x8_ne::<T>,
        vector_instructions::i16x8_lt_s::<T>,
        vector_instructions::i16x8_lt_u::<T>,
        vector_instructions::i16x8_gt_s::<T>,
        vector_instructions::i16x8_gt_u::<T>,
        vector_instructions::i16x8_le_s::<T>,
        vector_instructions::i16x8_le_u::<T>,
        vector_instructions::i16x8_ge_s::<T>,
        vector_instructions::i16x8_ge_u::<T>,
        // 55
        vector_instructions::i32x4_eq::<T>,
        vector_instructions::i32x4_ne::<T>,
        vector_instructions::i32x4_lt_s::<T>,
        vector_instructions::i32x4_lt_u::<T>,
        vector_instructions::i32x4_gt_s::<T>,
        vector_instructions::i32x4_gt_u::<T>,
        vector_instructions::i32x4_le_s::<T>,
        vector_instructions::i32x4_le_u::<T>,
        vector_instructions::i32x4_ge_s::<T>,
        vector_instructions::i32x4_ge_u::<T>,
        // 65
        vector_instructions::f32x4_eq::<T>,
        vector_instructions::f32x4_ne::<T>,
        vector_instructions::f32x4_lt::<T>,
        vector_instructions::f32x4_gt::<T>,
        vector_instructions::f32x4_le::<T>,
        vector_instructions::f32x4_ge::<T>,
        // 71
        vector_instructions::f64x2_eq::<T>,
        vector_instructions::f64x2_ne::<T>,
        vector_instructions::f64x2_lt::<T>,
        vector_instructions::f64x2_gt::<T>,
        vector_instructions::f64x2_le::<T>,
        vector_instructions::f64x2_ge::<T>,
        // 77
        vector_instructions::v128_not::<T>,
        vector_instructions::v128_and::<T>,
        vector_instructions::v128_andnot::<T>,
        vector_instructions::v128_or::<T>,
        vector_instructions::v128_xor::<T>,
        vector_instructions::v128_bitselect::<T>,
        vector_instructions::v128_any_true::<T>,
        // 84
        memory_instructions::v128_load8_lane::<T>,
        memory_instructions::v128_load16_lane::<T>,
        memory_instructions::v128_load32_lane::<T>,
        memory_instructions::v128_load64_lane::<T>,
        memory_instructions::v128_store8_lane::<T>,
        memory_instructions::v128_store16_lane::<T>,
        memory_instructions::v128_store32_lane::<T>,
        memory_instructions::v128_store64_lane::<T>,
        memory_instructions::v128_load32_zero::<T>,
        memory_instructions::v128_load64_zero::<T>,
        // 94
        vector_instructions::f32x4_demote_f64x2_zero::<T>,
        vector_instructions::f64x2_promote_low_f32x4::<T>,
        // 96
        vector_instructions::i8x16_abs::<T>,
        vector_instructions::i8x16_neg::<T>,
        vector_instructions::i8x16_popcnt::<T>,
        vector_instructions::i8x16_all_true::<T>,
        vector_instructions::i8x16_bitmask::<T>,
        vector_instructions::i8x16_narrow_i16x8_s::<T>,
        vector_instructions::i8x16_narrow_i16x8_u::<T>,
        // 103
        vector_instructions::f32x4_ceil::<T>,
        vector_instructions::f32x4_floor::<T>,
        vector_instructions::f32x4_trunc::<T>,
        vector_instructions::f32x4_nearest::<T>,
        // 107
        vector_instructions::i8x16_shl::<T>,
        vector_instructions::i8x16_shr_s::<T>,
        vector_instructions::i8x16_shr_u::<T>,
        vector_instructions::i8x16_add::<T>,
        vector_instructions::i8x16_add_sat_s::<T>,
        vector_instructions::i8x16_add_sat_u::<T>,
        vector_instructions::i8x16_sub::<T>,
        vector_instructions::i8x16_sub_sat_s::<T>,
        vector_instructions::i8x16_sub_sat_u::<T>,
        // 116
        vector_instructions::f64x2_ceil::<T>,
        vector_instructions::f64x2_floor::<T>,
        // 118
        vector_instructions::i8x16_min_s::<T>,
        vector_instructions::i8x16_min_u::<T>,
        vector_instructions::i8x16_max_s::<T>,
        vector_instructions::i8x16_max_u::<T>,
        // 122
        vector_instructions::f64x2_trunc::<T>,
        // 123
        vector_instructions::i8x16_avgr_u::<T>,
        // 124
        vector_instructions::i16x8_extadd_pairwise_i8x16_s::<T>,
        vector_instructions::i16x8_extadd_pairwise_i8x16_u::<T>,
        // 126
        vector_instructions::i32x4_extadd_pairwise_i16x8_s::<T>,
        vector_instructions::i32x4_extadd_pairwise_i16x8_u::<T>,
        // 128
        vector_instructions::i16x8_abs::<T>,
        vector_instructions::i16x8_neg::<T>,
        vector_instructions::i16x8_q15mulrsat_s::<T>,
        vector_instructions::i16x8_all_true::<T>,
        vector_instructions::i16x8_bitmask::<T>,
        vector_instructions::i16x8_narrow_i32x4_s::<T>,
        vector_instructions::i16x8_narrow_i32x4_u::<T>,
        vector_instructions::i16x8_extend_low_i8x16_s::<T>,
        vector_instructions::i16x8_extend_high_i8x16_s::<T>,
        vector_instructions::i16x8_extend_low_i8x16_u::<T>,
        vector_instructions::i16x8_extend_high_i8x16_u::<T>,
        vector_instructions::i16x8_shl::<T>,
        vector_instructions::i16x8_shr_s::<T>,
        vector_instructions::i16x8_shr_u::<T>,
        vector_instructions::i16x8_add::<T>,
        vector_instructions::i16x8_add_sat_s::<T>,
        vector_instructions::i16x8_add_sat_u::<T>,
        vector_instructions::i16x8_sub::<T>,
        vector_instructions::i16x8_sub_sat_s::<T>,
        vector_instructions::i16x8_sub_sat_u::<T>,
        // 148
        vector_instructions::f64x2_nearest::<T>,
        // 149
        vector_instructions::i16x8_mul::<T>,
        vector_instructions::i16x8_min_s::<T>,
        vector_instructions::i16x8_min_u::<T>,
        vector_instructions::i16x8_max_s::<T>,
        vector_instructions::i16x8_max_u::<T>,
        // 154
        unset::<T>,
        // 155
        vector_instructions::i16x8_avgr_u::<T>,
        vector_instructions::i16x8_extmul_low_i8x16_s::<T>,
        vector_instructions::i16x8_extmul_high_i8x16_s::<T>,
        vector_instructions::i16x8_extmul_low_i8x16_u::<T>,
        vector_instructions::i16x8_extmul_high_i8x16_u::<T>,
        // 160
        vector_instructions::i32x4_abs::<T>,
        vector_instructions::i32x4_neg::<T>,
        // 162
        unset::<T>,
        // 163
        vector_instructions::i32x4_all_true::<T>,
        vector_instructions::i32x4_bitmask::<T>,
        // 165,
        unset::<T>,
        unset::<T>,
        // 167
        vector_instructions::i32x4_extend_low_i16x8_s::<T>,
        vector_instructions::i32x4_extend_high_i16x8_s::<T>,
        vector_instructions::i32x4_extend_low_i16x8_u::<T>,
        vector_instructions::i32x4_extend_high_i16x8_u::<T>,
        vector_instructions::i32x4_shl::<T>,
        vector_instructions::i32x4_shr_s::<T>,
        vector_instructions::i32x4_shr_u::<T>,
        vector_instructions::i32x4_add::<T>,
        // 175
        unset::<T>,
        unset::<T>,
        // 177
        vector_instructions::i32x4_sub::<T>,
        // 178
        unset::<T>,
        unset::<T>,
        unset::<T>,
        // 181
        vector_instructions::i32x4_mul::<T>,
        vector_instructions::i32x4_min_s::<T>,
        vector_instructions::i32x4_min_u::<T>,
        vector_instructions::i32x4_max_s::<T>,
        vector_instructions::i32x4_max_u::<T>,
        vector_instructions::i32x4_dot_i16x8_s::<T>,
        // 187
        unset::<T>,
        // 188
        vector_instructions::i32x4_extmul_low_i16x8_s::<T>,
        vector_instructions::i32x4_extmul_high_i16x8_s::<T>,
        vector_instructions::i32x4_extmul_low_i16x8_u::<T>,
        vector_instructions::i32x4_extmul_high_i16x8_u::<T>,
        // 192
        vector_instructions::i64x2_abs::<T>,
        vector_instructions::i64x2_neg::<T>,
        // 194
        unset::<T>,
        // 195
        vector_instructions::i64x2_all_true::<T>,
        vector_instructions::i64x2_bitmask::<T>,
        // 197
        unset::<T>,
        unset::<T>,
        // 199
        vector_instructions::i64x2_extend_low_i32x4_s::<T>,
        vector_instructions::i64x2_extend_high_i32x4_s::<T>,
        vector_instructions::i64x2_extend_low_i32x4_u::<T>,
        vector_instructions::i64x2_extend_high_i32x4_u::<T>,
        vector_instructions::i64x2_shl::<T>,
        vector_instructions::i64x2_shr_s::<T>,
        vector_instructions::i64x2_shr_u::<T>,
        vector_instructions::i64x2_add::<T>,
        // 207
        unset::<T>,
        unset::<T>,
        // 209
        vector_instructions::i64x2_sub::<T>,
        // 210
        unset::<T>,
        unset::<T>,
        unset::<T>,
        // 213
        vector_instructions::i64x2_mul::<T>,
        // 214
        vector_instructions::i64x2_eq::<T>,
        vector_instructions::i64x2_ne::<T>,
        vector_instructions::i64x2_lt_s::<T>,
        vector_instructions::i64x2_gt_s::<T>,
        vector_instructions::i64x2_le_s::<T>,
        vector_instructions::i64x2_ge_s::<T>,
        // 220
        vector_instructions::i64x2_extmul_low_i32x4_s::<T>,
        vector_instructions::i64x2_extmul_high_i32x4_s::<T>,
        vector_instructions::i64x2_extmul_low_i32x4_u::<T>,
        vector_instructions::i64x2_extmul_high_i32x4_u::<T>,
        // 224
        vector_instructions::f32x4_abs::<T>,
        vector_instructions::f32x4_neg::<T>,
        // 226
        unset::<T>,
        // 227
        vector_instructions::f32x4_sqrt::<T>,
        vector_instructions::f32x4_add::<T>,
        vector_instructions::f32x4_sub::<T>,
        vector_instructions::f32x4_mul::<T>,
        vector_instructions::f32x4_div::<T>,
        vector_instructions::f32x4_min::<T>,
        vector_instructions::f32x4_max::<T>,
        vector_instructions::f32x4_pmin::<T>,
        vector_instructions::f32x4_pmax::<T>,
        // 236
        vector_instructions::f64x2_abs::<T>,
        vector_instructions::f64x2_neg::<T>,
        // 238
        unset::<T>,
        // 239
        vector_instructions::f64x2_sqrt::<T>,
        vector_instructions::f64x2_add::<T>,
        vector_instructions::f64x2_sub::<T>,
        vector_instructions::f64x2_mul::<T>,
        vector_instructions::f64x2_div::<T>,
        vector_instructions::f64x2_min::<T>,
        vector_instructions::f64x2_max::<T>,
        vector_instructions::f64x2_pmin::<T>,
        vector_instructions::f64x2_pmax::<T>,
        // 248
        vector_instructions::i32x4_trunc_sat_f32x4_s::<T>,
        vector_instructions::i32x4_trunc_sat_f32x4_u::<T>,
        // 250
        vector_instructions::f32x4_convert_i32x4_s::<T>,
        vector_instructions::f32x4_convert_i32x4_u::<T>,
        // 252
        vector_instructions::i32x4_trunc_sat_f64x2_s_zero::<T>,
        vector_instructions::i32x4_trunc_sat_f64x2_u_zero::<T>,
        // 254
        vector_instructions::f64x2_convert_low_i32x4_s::<T>,
        vector_instructions::f64x2_convert_low_i32x4_u::<T>,
        // todo
    ];
}
