[package]
name = "compare-testsuite-rs"
description = """
A program that compares two sets of specification testsuite results produced by dlr-wasm-interpreter
"""

edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
itertools = "0.14"
