[package]
name = "dlr-wasm-interpreter-interop"
description = """
Interoperation between Rust and Wasm types for dlr-wasm-interpreter through automatic type conversion
"""

edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
dlr-wasm-interpreter.workspace = true
