name: Nix based CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Nix Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check .?submodules=1

  build-test-cover-document:
    name: Nix build wasm-interpreter and report
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#wasm-interpreter --print-build-logs
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          file: result/lcov-codecov.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: nix build .?submodules=1#report --print-build-logs
      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: result/

  build-test-32bit:
    name: Test for 32 bit target
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#wasm-interpreter-cross-i686-linux --print-build-logs
