name: Nix Related Actions

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Nix Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run Checks
        run: nix flake check

  build-test-cover-document:
    name: Nix build wasm-interpreter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run Checks
        run: nix build .#wasm-interpreter --print-build-logs
