name: Nix based CI

on:
  push:
    branches-ignore:
      - "gh-readonly-queue/**"
      - "gh-pages"
  merge_group:

jobs:
  checks:
    name: Nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check .?submodules=1

  bench:
    name: Nix benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#benchmark --print-build-logs

  build:
    name: Nix build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#wasm-interpreter --print-build-logs

  cover:
    name: Nix coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#coverage --print-build-logs
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          file: result/lcov-codecov.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  report:
    name: Nix report
    needs: [bench, build, cover, requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#report --print-build-logs
      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: result/

  requirements:
    name: Nix generate requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#requirements --print-build-logs

  build-test-32bit:
    name: Test for 32 bit target
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .?submodules=1#packages.i686-linux.wasm-interpreter --print-build-logs
