name: No-Nix based CI

on:
  push:
    branches-ignore:
      - "gh-readonly-queue/**"
      - "gh-pages"
  merge_group:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      # for CI we can treat warnings as errors
      # for reference see: https://doc.rust-lang.org/clippy/usage.html
      RUSTFLAGS: "-D warnings"
      RUSTDOCFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Versions
        run: cargo --version && rustc --version
      - name: Format
        run: cargo check
      - name: Run clippy
        run: cargo clippy
      - name: Build docs
        run: cargo doc --document-private-items --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --nocapture

  conventional-commit-check:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: webiny/action-conventional-commits@v1.3.0

  msrv-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack check --rust-version --workspace --all-targets --ignore-private --ignore-rust-version
